name: Build QEMU Full macOS ARM64

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-14 # Apple Silicon runner

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        brew update
        brew install \
          pkg-config glib pixman ninja libslirp jpeg libpng \
          usbredir zlib libffi gettext autoconf automake \
          libtool cmake swtpm spice-protocol spice \
          gtk+3 libepoxy libusb

    - name: Clone QEMU
      run: |
        git clone https://gitlab.com/qemu-project/qemu.git
        cd qemu
        git checkout v9.0.1

    - name: Configure QEMU
      run: |
        cd qemu
        ./configure \
          --target-list=aarch64-softmmu \
          --enable-hvf \
          --enable-cocoa \
          --enable-slirp \
          --enable-tpm \
          --enable-spice \
          --enable-usb-redir \
          --enable-virtfs \
          --enable-opengl \
          --enable-gtk \
          --enable-lto \
          --disable-sdl

    - name: Build QEMU
      run: |
        cd qemu
        make -j$(sysctl -n hw.ncpu)

    - name: Package Artifacts
      run: |
        mkdir -p output
        cp qemu/build/*-softmmu/qemu-system-* output/
        tar -czf qemu-macos-arm64.tar.gz output

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: qemu-macos-arm64
        path: qemu-macos-arm64.tar.gz
